### ISSUE TITLE
uglifyjs: command not found on npm run build

### ISSUE THREAD

**Issue by denormalizer** [arthur-e/Wicket#106]
How to reproduce

    [username@server proj]$ bower install -S Wicket
    bower Wicket#*   cached https://github.com/arthur-e/Wicket.git#1.3.2
    bower Wicket#*   validate 1.3.2 against https://github.com/arthur-e/Wicket.git#*
    [username@server proj]$ cd vendor/Wicket
    [username@server proj]$ npm run build

Error short:

    sh: uglifyjs: command not found

OS: CentOS 7 64 bit

**Comment by denormalizer** [comment]
npm-debug.log

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
    2 info using npm@2.15.1
    3 info using node@v0.10.46
    4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
    5 info prebuild wicket@1.3.1
    6 info build wicket@1.3.1
    7 verbose unsafe-perm in lifecycle true
    8 info wicket@1.3.1 Failed to exec build script
    9 verbose stack Error: wicket@1.3.1 build: `uglifyjs wicket.js -o wicket.min.js;uglifyjs wicket-gmap3.js -o wicket-gmap3.min.js;uglifyjs wicket-arcgis.js -o wicket-arcgis.min.js;uglifyjs wicket-leaflet.js -o wicket-leaflet.min.js;`
    9 verbose stack spawn ENOENT
    9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:17:16)
    9 verbose stack     at ChildProcess.emit (events.js:98:17)
    9 verbose stack     at maybeClose (child_process.js:766:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
    10 verbose pkgid wicket@1.3.1
    11 verbose cwd /var/www/proj/vendor/Wicket
    12 error Linux 3.10.0-229.1.2.el7.x86_64
    13 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    14 error node v0.10.46
    15 error npm  v2.15.1
    16 error file sh
    17 error code ELIFECYCLE
    18 error errno ENOENT
    19 error syscall spawn
    20 error wicket@1.3.1 build: `uglifyjs wicket.js -o wicket.min.js;uglifyjs wicket-gmap3.js -o wicket-gmap3.min.js;uglifyjs wicket-arcgis.js -o wicket-arcgis.min.js;uglifyjs wicket-leaflet.js -o wicket-leaflet.min.js;`
    20 error spawn ENOENT
    21 error Failed at the wicket@1.3.1 build script 'uglifyjs wicket.js -o wicket.min.js;uglifyjs wicket-gmap3.js -o wicket-gmap3.min.js;uglifyjs wicket-arcgis.js -o wicket-arcgis.min.js;uglifyjs wicket-leaflet.js -o wicket-leaflet.min.js;'.
    21 error This is most likely a problem with the wicket package,
    21 error not with npm itself.
    21 error Tell the author that this fails on your system:
    21 error     uglifyjs wicket.js -o wicket.min.js;uglifyjs wicket-gmap3.js -o wicket-gmap3.min.js;uglifyjs wicket-arcgis.js -o wicket-arcgis.min.js;uglifyjs wicket-leaflet.js -o wicket-leaflet.min.js;
    21 error You can get information on how to open an issue for this project with:
    21 error     npm bugs wicket
    21 error Or if that isn't available, you can get their info via:
    21 error
    21 error     npm owner ls wicket
    21 error There is likely additional logging output above.
    22 verbose exit [ 1, true ]

**Comment by denormalizer** [comment]
npm install uglify-js -g
